spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER}
          audiences: ${AUDIENCES}

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173/"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE